version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ust2
      MYSQL_ROOT_PASSWORD: root